version: '3'

services:
  graphrag:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - OLLAMA_BASE_URL=http://<ollama ip>11434
      # Try multiple connection options
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphragpassword
      # Streamlit performance optimizations
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=200
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_LOGGER_LEVEL=error
      - PYTHONUNBUFFERED=1
    depends_on:
      - neo4j
    restart: unless-stopped
    networks:
      - graphrag-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    command: >
      sh -c "
        echo 'Waiting for Neo4j to be ready...' &&
        sleep 30 &&
        echo 'Starting Streamlit app...' &&
        streamlit run app.py --server.maxUploadSize=200 --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=true
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"

  neo4j:
    image: neo4j:5.14.0
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/graphragpassword
      # Performance optimizations - reduced for better compatibility
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
      # Network settings
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0:7474
      - NEO4J_dbms_connector_https_listen__address=0.0.0.0:7473
      - NEO4J_dbms_connector_bolt_advertised__address=neo4j:7687
      - NEO4J_dbms_connector_http_advertised__address=neo4j:7474
      # Plugin settings
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    restart: unless-stopped
    networks:
      - graphrag-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  graphrag-network:
    driver: bridge
    name: graphrag-network
